cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    # 아래 두 코드는 같은 기능이나 방법이 두가지여서 각각 사용함.
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<product_id>/', remove, name='product_remove'),
]

mixdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls')),
    path("", index_view, name='home')
]

users/urls.py
from django.urls import path
from .views import *



app_name = 'users'

urlpatterns = [
    path('sing_up_main/', singup_main,name='sing_up_main'),
    path('user_sing_up/', Customer_Singup_View.as_view(),name='user_sing_up'),
    path('seller_sing_up/', Seller_Singup_View.as_view(),name='seller_sing_up'),
    path('buyer_sing_up/', Buyer_Singup_View.as_view(),name='buyer_sing_up'),
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', log_out,name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class NormalUser(AbstractUser):
    mobile = models.CharField(max_length=20, null=True)
    post_code = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=40, null=True)
    detail_address = models.CharField(max_length=100, null=True)
    profile_pic = models.FileField(upload_to='media/', null=True, blank=True)

class Seller(models.Model):
    user = models.OneToOneField(NormalUser, on_delete=models.CASCADE, primary_key=True)
    company = models.CharField(max_length=20, null=True)
    company_profile = models.FileField(upload_to='media/', null=True, blank=True)

class Buyer(models.Model):
    user = models.OneToOneField(NormalUser, on_delete=models.CASCADE, primary_key=True)
    company = models.CharField(max_length=20, null=True)
    company_profile = models.FileField(upload_to='media/', null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import *
from django.db import transaction



class NormalUserForm(UserCreationForm):
    mobile = forms.CharField(required=True)
    post_code = forms.CharField(required=True)
    address = forms.CharField(required=True)
    detail_address = forms.CharField(required=True)
    profile_pic = forms.FileField(required=True)
    # email = forms.EmailField()
    class Meta(UserCreationForm.Meta):
        model = NormalUser

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.mobile = self.cleaned_data.get('mobile')
        user.post_code = self.cleaned_data.get('post_code')
        user.address = self.cleaned_data.get('address')
        user.detail_address = self.cleaned_data.get('detail_address')
        user.profile_pic = self.cleaned_data.get('profile_pic')
        # user.email = self.cleaned_data.get('email')
        user.save()
        return user

class SellerForm(UserCreationForm):
    mobile = forms.CharField(required=True)
    post_code = forms.CharField(required=True)
    address = forms.CharField(required=True)
    detail_address = forms.CharField(required=True)
    company = forms.CharField(required=True)
    company_profile = forms.FileField(required=True)

    class Meta(UserCreationForm.Meta):
        model = NormalUser

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.mobile = self.cleaned_data.get('mobile')
        user.post_code = self.cleaned_data.get('post_code')
        user.address = self.cleaned_data.get('address')
        user.detail_address = self.cleaned_data.get('detail_address')
        user.save()
        seller = Seller.objects.create(user=user)
        seller.company = self.cleaned_data.get('company')
        seller.company_profile=self.cleaned_data.get('company_profile')
        seller.save()
        return user


class BuyerForm(UserCreationForm):
    mobile = forms.CharField(required=True)
    post_code = forms.CharField(required=True)
    address = forms.CharField(required=True)
    detail_address = forms.CharField(required=True)
    company = forms.CharField(required=True)
    company_profile = forms.FileField(required=True)

    class Meta(UserCreationForm.Meta):
        model = NormalUser

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.mobile = self.cleaned_data.get('mobile')
        user.post_code = self.cleaned_data.get('post_code')
        user.address = self.cleaned_data.get('address')
        user.detail_address = self.cleaned_data.get('detail_address')
        user.save()
        buyer = Buyer.objects.create(user=user)
        buyer.company = self.cleaned_data.get('company')
        buyer.company_profile=self.cleaned_data.get('company_profile')
        buyer.save()
        return user

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data.get('username') # 유효성 검사를 진행한 username field에 값을 추출
        password = self.cleaned_data.get('password') # 유효성 검사를 진행한 password field에 값을 추출
        try:
            user = NormalUser.objects.get(username=username) # username을 기준으로 해당 Object를 가져옴
            if user.check_password(password): # 비밀번호가 서로 일치한다면 True, 아니면 False 반환 
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except NormalUser.DoesNotExist:
            self.add_error("username", forms.ValidationError("User does not exist"))

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, reverse
from users.forms import *
from django.views.generic import CreateView
from django.views import View


# Create your views here.

def index_view(request):
    return render(request, 'base.html')

def singup_main(request):
    return render(request, 'registermain.html')

def login_view(request):
    return render(request, 'login.html')

class Customer_Singup_View(CreateView):
    model = NormalUser
    form_class = NormalUserForm
    template_name = 'customer_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')

class Seller_Singup_View(CreateView):
    model = NormalUser
    form_class = SellerForm
    template_name = 'seller_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')

class Buyer_Singup_View(CreateView):
    model = NormalUser
    form_class = BuyerForm
    template_name = 'buyer_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')

class LoginView(View):
    def get(self, request):
        form = LoginForm()
        context = {"form":form}
        return render(request, "login.html", context) # 빈 form을 제공
    
    def post(self, request):
        form = LoginForm(request.POST) # 사용자의 입력값을 유지
        if form.is_valid(): # 유효성 검사 결과가 True라면
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
        context = {"form":form}
        return render(request, "login.html", context)

def log_out(request):
    logout(request)
    return redirect("home")

users/templates/bootlogin.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
  	<title>Login 01</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login #01</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<div class="icon d-flex align-items-center justify-content-center">
		      		<span class="fa fa-user-o"></span>
		      	</div>
		      	<h3 class="text-center mb-4">Sign In</h3>
						<form action="#" class="login-form">
		      		<div class="form-group">
		      			<input type="text" class="form-control rounded-left" placeholder="Username" required>
		      		</div>
	            <div class="form-group d-flex">
	              <input type="password" class="form-control rounded-left" placeholder="Password" required>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="form-control btn btn-primary rounded submit px-3">Login</button>
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
	            		<label class="checkbox-wrap checkbox-primary">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="{% url 'users:sing_up_main' %}">Sing up</a>
								</div>
	            </div>
	          </form>
	        </div>
				</div>
			</div>
		</div>
	</section>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

users/templates/buyer_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>바이어</title>
</head>
<body>
    <div class="container">
        <form class="box" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>buyer</h1>
                {% for field in form.visible_fields %}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% endfor %}
            <input type="submit" name="" value="Create">
        </form>
    </div>
</body>
</html>

users/templates/customer_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cutomer</title>
</head>
<body>
    <div class="container">
        <form class="box" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Customer</h1>
                {% for field in form.visible_fields %}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% endfor %}
            <input type="submit" name="" value="Create">
        </form>
    </div>
</body>
</html>

users/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    <h1>test page</h1>
    <div class="container">
        <div class="row row1">
            <ul class="largenav pull-right">
                <li class="upper-links dropdown"><a class="links" href="">Login & SignUp</a>
                    <ul class="dropdown-menu">
                        <li class="profile-li"><a class="profile-links" href="{% url 'login' %}">Login</a></li>
                        <li class="profile-li"><a class="profile-links" href="{% url 'register_main' %}">Signup</a></li>
                        <li class="profile-li"><a class="profile-links" href="{% url 'product_register' %}">Product register</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</body>
</html>

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>LOGIN</h4>
        </div>
        <div>
            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit">
            </form>
        </div>
    </div>
</body>
</html>

users/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>logout</title>
</head>
<body>
    
</body>
</html>

users/templates/product_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="test_register">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" name="" value="Create">
        </form>
    </div>
</body>
</html>

users/templates/registermain.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입메인</title>
</head>
<body>
    <div>
        <a class="profile-links" href="{% url 'users:user_sing_up' %}">Customer</a></li>
        <a class="profile-links" href="{% url 'users:seller_sing_up' %}">Seller</a></li>
        <a class="profile-links" href="{% url 'users:buyer_sing_up' %}">Buyer</a></li>
        <!-- <button onclick="location.href='c_register'">일반회원</button>
        <button onclick="location.href='s_register'">셀러</button>
        <button onclick="location.href='b_register'">바이어</button> -->
    </div>
    

</body>
</html>

users/templates/seller_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>셀러</title>
</head>
<body>
    <div class="container">
        <form class="box" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>seller</h1>
                {% for field in form.visible_fields %}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% endfor %}
            <input type="submit" name="" value="Create">
        </form>
    </div>
</body>
</html>