cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    # 아래 두 코드는 같은 기능이나 방법이 두가지여서 각각 사용함.
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<product_id>/', remove, name='product_remove'),
]

mixdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls')),
    path("", index_view, name='home')
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop' # 이것이 있기 때문에 model에서 shop:product_detail 코드가 작성 가능해지는 것임.
urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'), # slug:category_slug의 : 뒤의 category_slug은 view의 product_in_category 함수의 파라미터에서 가져옴.
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'), # :부분을 안쓰고 이렇게 작성해도 동작은 됨. 크게 상관 없음.
    path('product_register', Product_Register.as_view(), name='product_register')
]

users/urls.py
from django.urls import path
from .views import *



app_name = 'users'

urlpatterns = [
    path('sing_up_main/', singup_main,name='sing_up_main'),
    path('user_sing_up/', Customer_Singup_View.as_view(),name='user_sing_up'),
    path('seller_sing_up/', Seller_Singup_View.as_view(),name='seller_sing_up'),
    path('buyer_sing_up/', Buyer_Singup_View.as_view(),name='buyer_sing_up'),
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', log_out,name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://code.jquery.com/jquery-3.6.1.min.js" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    {% block script %}
    {% endblock %}

    {% block style %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Test Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav justify-content-end">
            <li class="nav-item" >
              <a class="nav-link" href='/'>Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:product_all' %}">Product</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:detail' %}">Cart</a>
                {% if cart|length > 0 %}
                    ${{cart.get_product_total}} with {{cart|length}} items
                {% else %}
                    : Empty
                {% endif %}
              </li>
              {% if user.is_authenticated %}
              <li>
                <p>
                  Welcome{{users.Username}}
                </p>
              </li>
              <li class="nav-item">
                <a class="nav-lik" href="{% url 'users:logout' %}">Logout</a>
              </li>

              <il class="nav-item">
                <a class="nav-lik" href="{% url 'shop:product_register' %}">Register Product</a>
              </il>

              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
              {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
<div class="container">
    {% block content %}
    {% endblock %}
    
</div>

</body>
</html>