cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    # 아래 두 코드는 같은 기능이나 방법이 두가지여서 각각 사용함.
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<product_id>/', remove, name='product_remove'),
]

mixdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls')),
    path("", index_view, name='home')
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop' # 이것이 있기 때문에 model에서 shop:product_detail 코드가 작성 가능해지는 것임.
urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'), # slug:category_slug의 : 뒤의 category_slug은 view의 product_in_category 함수의 파라미터에서 가져옴.
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'), # :부분을 안쓰고 이렇게 작성해도 동작은 됨. 크게 상관 없음.
    path('product_register', Product_Register.as_view(), name='product_register')
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
# 배프의 오지랖 파이썬 웹프로그래밍

class Category(models.Model): # 사용자는 선택만 할 수 있도록 admin에 서 생성하도록
    name = models.CharField(max_length=200, db_index=True)
    meta_description = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_in_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    meta_description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created', '-updated']
        index_together = [['id','slug']]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/forms.py
'''
12.19 error product save 안됨
'''
from django import forms

from django.db import transaction
from shop.models import *

class ProductForm(forms.ModelForm): # modelform으로 받아야함
    name = forms.CharField(required=True)
    slug = forms.SlugField(required=True)
    image = forms.FileField(required=True)
    description = forms.CharField(required=True)
    meta_description = forms.CharField(required=True)
    price = forms.DecimalField(required=True)
    stock = forms.CharField(required=True)
    available_display = forms.BooleanField(required=True)
    available_order = forms.BooleanField(required=True)

    class Meta():
        model = Product
        fields = '__all__'

    @transaction.atomic
    def save(self):
        product = Product.objects.get(pk=self.cleaned_data['pk'])
        product.name = self.cleaned_data.get('name')
        product.slug = self.cleaned_data.get('slug')
        product.image = self.cleaned_data.get('image')
        product.description = self.cleaned_data.get('description')
        product.meta_description = self.cleaned_data.get('meta_description')
        product.price = self.cleaned_data.get('price')
        product.stock = self.cleaned_data.get('stock')
        product.available_display = self.cleaned_data.get('available_display')
        product.available_order = self.cleaned_data.get('available_order')
        product.save()

        return product

shop/views.py
'''
12.19 error product save 안됨
'''

from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView
from .models import *
from .forms import *
from cart.forms import AddProductForm
from django.contrib import messages

# Create your views here.
def product_in_category(request, category_slug=None): # pageing 작업 추가하기!!!
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True) # 표시 가능한 애들만 불러오겠다.
    
    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug) # Category model에서 slug가 category_slug인 애들만 불러올꺼야 아닐 시 404로 보내~
        products = products.filter(category=current_category) # 쿼리는 매번 실행되는 것이 아니라 데이터를 필요로 하는 때에만 실행되기 때문에 속도에 영향을 크게 미치지 않는다 그렇게에 마음껏 사용해도 됨.

    return render(request, 'shop/list.html', {
        'current_category':current_category,
        'categories':categories,
        'products':products
    })

def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity':1})
    return render(request, 'shop/detail.html', {'product':product, 'add_to_cart':add_to_cart})

class Product_Register(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_register.html'

    @transaction.atomic
    def form_valid(self):
        self.save()

        return redirect('product_register')

shop/templates/shop/detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="col">
                <img src="{{product.image.url}}" width="100%">
            </div>
        </div>
        <div class="col">
            <h1 class="display-6">{{product.name}}</h1>
            <p><span class="badge badge-secondary">Price</span>{{product.price}}</p>

            <form action="{% url 'cart:product_add' product.id %}" method="post">
                {{add_to_cart}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary btn-sm" value="Add to Cart">
            </form>

            <h5><span class="badge badge-secondary">Description</span>{{product.description|linebreaks}}</h5>
        </div>
    </div>
{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}

{% block title %}Category Page
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-2">
        <div class="list-group">
            <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">All</a>
            {% for c in categories %}
             <a href="{{c.get_absolute_url}}" class="list-group-item {% if current_category.slug == c.slug %}active{% endif %}">{{c.name}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col">
        <div class="alert alert-info">
            {% if current_category %}{{current_category.name}}{% else %}All Products{% endif %}
        </div>
        <div class="row">
            {% for product in products %}
            <div class="col-4">
                <div class="card">
                    {%if product.image%}<img class="cart-img-top" src="{{product.image.url}}" alt="Product Image" style="width:100%;">{%endif%}
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">{{product.description}} <span class="badge badge-secondary">{{product.price}}</span></p>
                        <a href="{{product.get_absolute_url}}" class="btn btn-primary">View Detail</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

shop/templates/shop/product_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Register</title>
</head>
<body>
    <div class="container">
        <form class="box" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Product Register</h1>
                {% for field in form.visible_fields %}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% endfor %}
            <input type="submit" name="" value="Create">
        </form>
    </div>
</body>
</html>